# promise then 和 catch 的链接

```javascript
// 场景 1
Promise.resolve()
.then(() => {
    console.log(1);
})
.catch(() => {
    console.log(2);
})
.then(() => {
    console.log(3);
})
// 1
// 3
```

```javascript
// 场景 2
Promise.resolve()
.then(() => {
    console.log(1);
    throw new Error("error1");
})
.catch(() => {
    console.log(2);
})
.then(() => {
    console.log(3);
})
// 1
// 2
// 3
```

```javascript
// 场景 3
Promise.resolve()
.then(() => {
    console.log(1);
    throw new Error("error1");
})
.catch(() => {
    console.log(2);
})
.catch(() => {
    console.log(3);
})
// 1
// 2
// 这里为什么？
```
